// Mocks generated by Mockito 5.4.5 from annotations
// in clean_architecture/test/get_all_traffic_sign_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:clean_architecture/features/dashboard/data/datasources/traffic_sign_remote_datasource.dart'
    as _i2;
import 'package:clean_architecture/features/dashboard/data/models/traffic_sign_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TrafficSignRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrafficSignRemoteDatasource extends _i1.Mock
    implements _i2.TrafficSignRemoteDatasource {
  MockTrafficSignRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.TrafficSignModel>> getAllTrafficSign() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTrafficSign, []),
            returnValue: _i3.Future<List<_i4.TrafficSignModel>>.value(
              <_i4.TrafficSignModel>[],
            ),
          )
          as _i3.Future<List<_i4.TrafficSignModel>>);

  @override
  _i3.Future<List<_i4.TrafficSignModel>> getAllTrafficSignById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAllTrafficSignById, [id]),
            returnValue: _i3.Future<List<_i4.TrafficSignModel>>.value(
              <_i4.TrafficSignModel>[],
            ),
          )
          as _i3.Future<List<_i4.TrafficSignModel>>);

  @override
  _i3.Future<List<_i4.TrafficSignModel>> getAllTrafficSignByType(
    String? type,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllTrafficSignByType, [type]),
            returnValue: _i3.Future<List<_i4.TrafficSignModel>>.value(
              <_i4.TrafficSignModel>[],
            ),
          )
          as _i3.Future<List<_i4.TrafficSignModel>>);

  @override
  _i3.Future<List<_i4.TrafficSignModel>> getAllTrafficSignByName(
    String? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllTrafficSignByName, [name]),
            returnValue: _i3.Future<List<_i4.TrafficSignModel>>.value(
              <_i4.TrafficSignModel>[],
            ),
          )
          as _i3.Future<List<_i4.TrafficSignModel>>);

  @override
  _i3.Future<List<_i4.TrafficSignModel>> getAllTrafficSignByIsAdded(
    bool? isAdded,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllTrafficSignByIsAdded, [isAdded]),
            returnValue: _i3.Future<List<_i4.TrafficSignModel>>.value(
              <_i4.TrafficSignModel>[],
            ),
          )
          as _i3.Future<List<_i4.TrafficSignModel>>);

  @override
  _i3.Future<List<_i4.TrafficSignModel>> getAllTrafficSignByIsNotAdded(
    bool? isAdded,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllTrafficSignByIsNotAdded, [isAdded]),
            returnValue: _i3.Future<List<_i4.TrafficSignModel>>.value(
              <_i4.TrafficSignModel>[],
            ),
          )
          as _i3.Future<List<_i4.TrafficSignModel>>);
}
